package commands

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

const beansGitignore = "# Generated by beanstalk init\n.conversations/\n"

var errAlreadyInitialized = errors.New("this directory is already initialized")

func newInitCommand() *cobra.Command {
	return &cobra.Command{
		Use:   "init",
		Short: "Initialize a Beans-format task directory",
		Args:  cobra.NoArgs,
		RunE: func(command *cobra.Command, args []string) error {
			workingDirectory, err := os.Getwd()
			if err != nil {
				return fmt.Errorf("getting working directory: %w", err)
			}

			if err := initialize(workingDirectory); err != nil {
				return err
			}

			command.Println("Initialized .beans and .beans.yml")
			return nil
		},
	}
}

func initialize(workingDirectory string) error {
	beansDirectory := filepath.Join(workingDirectory, ".beans")
	configPath := filepath.Join(workingDirectory, ".beans.yml")
	gitignorePath := filepath.Join(beansDirectory, ".gitignore")

	if pathExists(beansDirectory) && pathExists(configPath) {
		return fmt.Errorf("%w: .beans and .beans.yml already exist", errAlreadyInitialized)
	}

	for _, path := range []string{beansDirectory, configPath, gitignorePath} {
		if _, err := os.Lstat(path); err == nil {
			return fmt.Errorf("refusing to overwrite existing %s", filepath.Base(path))
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("checking %s: %w", path, err)
		}
	}

	if err := os.Mkdir(beansDirectory, 0o755); err != nil {
		return fmt.Errorf("creating .beans directory: %w", err)
	}
	if err := os.WriteFile(gitignorePath, []byte(beansGitignore), 0o644); err != nil {
		return fmt.Errorf("creating .beans/.gitignore: %w", err)
	}
	if err := os.WriteFile(configPath, []byte(defaultConfig(filepath.Base(workingDirectory), baseRef(workingDirectory))), 0o644); err != nil {
		return fmt.Errorf("creating .beans.yml: %w", err)
	}

	return nil
}

func pathExists(path string) bool {
	_, err := os.Lstat(path)
	return err == nil
}

func baseRef(workingDirectory string) string {
	output, err := exec.Command("git", "-C", workingDirectory, "symbolic-ref", "--quiet", "--short", "refs/remotes/origin/HEAD").Output()
	if err != nil {
		return "main"
	}

	return strings.TrimSpace(string(output))
}

func defaultConfig(projectName, baseRef string) string {
	return fmt.Sprintf(`# Beans configuration
# See: https://github.com/hmans/beans
project:
  # Human-readable project name (displayed in the UI)
  name: %q
beans:
  # Directory where bean files are stored
  path: .beans
  # Prefix for bean IDs (e.g., "myproject-abc1")
  prefix: %q
  # Length of the random ID suffix
  id_length: 4
  # Default status for new beans
  default_status: todo
  # Default type for new beans
  default_type: task
worktree:
  # Git ref to use as the base for new worktree branches (default: main)
  base_ref: %q
  # Shell command to run inside a worktree after creation (e.g. "pnpm install")
  setup: ""
  # Shell command to run the project (adds a "Run" button to workspace toolbar)
  run: ""
  # Integration strategy: "local" (squash-merge locally) or "pr" (push and create PRs)
  integrate: local
agent:
  # Enable agent functionality in the web UI (true, false)
  enabled: true
  # Default mode for agent sessions (act, plan)
  default_mode: act
server:
  # Port for the web UI (used by beans-serve)
  port: 8080
`, projectName, projectName+"-", baseRef)
}
